apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qryn-helm.fullname" . }}
  labels:
  {{- include "qryn-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
    {{- include "qryn-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "qryn-helm.selectorLabels" . | nindent 8 }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ include "qryn-helm.fullname" . }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        env:
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: "{{ $val }}"
          {{- end }}

        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP

        {{- if eq .Values.livenessProbe.enabled true }}
        livenessProbe: 
          httpGet: 
            path: {{ .Values.livenessProbe.endpoint }}
            port: http
          initialDelaySeconds: 10 #Default 0 
          periodSeconds: 10 #Default 10 
          timeoutSeconds: 1 #Default 1 
          successThreshold: 1 #Default 1 
          failureThreshold: 3 #Default 3 
        {{ end }}

        resources:
          {{- toYaml .Values.resources | nindent 12 }}

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      restartPolicy: Always
      {{- if .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
      {{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
      {{ toYaml .Values.affinity | indent 8 }}
      {{- end }}

